### ISSUE TITLE
module 'openai' has no attribute 'InvalidRequestError'. Did you mean: 'BadRequestError'?

### ISSUE THREAD

**Issue by happyfmy** [WPeace-HcH/WPeChatGPT#24]
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:/xxxxxx/IDA_Pro_7.7/plugins/WPeChatGPT.py", line 280, in query_model
    except openai.InvalidRequestError as e:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'InvalidRequestError'. Did you mean: 'BadRequestError'?

**Comment by WPeace-HcH** [comment]
你好，和之前反馈的是同一个问题，由于使用的python旧版本openai包和新版本不兼容，你可以下载v2.4版本WPeChatGPT进行尝试。（如果pip更新了openai包还是出现此类错误，请确认IDA使用的python环境是否正确）

**Comment by WPeace-HcH** [comment]
v2.4及以前版本支持旧版本openai package
v2.5开始兼容新版本包，需要pip进行更新
